### ISSUE TITLE
Build channels for ILO content

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-library#12]
## Overview 

Prepare channels for these ILO courses:
- ILO's GET Ahead Training Package
- ILO's Financial Education Tool
- ILO's Start and Improve Your Business (SIYB)
- ILO's Start and Improve Your Business (SIYB) - PDF

#### Description and outcomes
Specs at https://docs.google.com/spreadsheets/d/18_urNiqv3DD4neteFBxfBc3ARCXv-5TRHFGFrPxnoxo/edit#gid=0

**Comment by jredrejo** [comment]
Finished ILO Start and Improve your business channel, available at https://studio.learningequality.org/en/channels/4752ba7fbade5ad88e06eb3bc79dd88c/  , token to test it in kolibri `tijom-zonab `

@rtibbles code to review at https://github.com/learningequality/sushi-chef-ilo-siyb

**Comment by radinamatic** [comment]
Tested the channel locally in all browsers on both Ubuntu 20.04 and Windows 10, HTML5 apps and PDF files all open without issues! 👏🏽 🎉 

I again downloaded the PDF files and opened in Acrobat Pro to see if they can be easily remediated to become at least partially accessible, but no dice: formatting is clearly meant for documents to be printed on paper, with scrambled semantic structure that would require way too much time to make accessible. Many documents are complex tables which are particularly thorny 😞 

I have 2 questions and 1 request for change:

1. [Source for **Start your business** is here](https://rise.articulate.com/share/0ZMyxNhhfd0hCuRJASzqOUSIGmvOmlKG#/), but I was not able to find the link for the **Improve your business**. Could you share that link?
2. I'm not seeing the **[Final self-assessment](https://rise.articulate.com/share/0ZMyxNhhfd0hCuRJASzqOUSIGmvOmlKG#/lessons/i4r1fkU45UL3hm3OnA98LPSY5qqMtyeb)** resource in the **Start your business**... 🤔 Was it an oversight or a conscious decision to omit it?
3. I know a lot of effort was invested into cheffing these, but we could improve the titles of the PDF resources by:
   a. Not using the acronyms SYB, IYB, GYB, but expand them fully to **Start your business**, **Improve your business**, and **Generate your business idea** (for clarity, especially if/when the resource is saved locally).
   b. Removing the ``.pdf`` ( $filename \ne title$ 😉 )

**Comment by jredrejo** [comment]
> Tested the channel locally in all browsers on both Ubuntu 20.04 and Windows 10, HTML5 apps and PDF files all open without issues! 👏🏽 🎉

Thanks for the review, this is unvaluable


> 
> I again downloaded the PDF files and opened in Acrobat Pro to see if they can be easily remediated to become at least partially accessible, but no dice: formatting is clearly meant for documents to be printed on paper, with scrambled semantic structure that would require way too much time to make accessible. Many documents are complex tables which are particularly thorny 😞
> 

if there is any automated tool that can be passed over them to improve them, I'll do it gladly. I'm all ears-

> I have 2 questions and 1 request for change:
> 
> 1. [Source for **Start your business** is here](https://rise.articulate.com/share/0ZMyxNhhfd0hCuRJASzqOUSIGmvOmlKG#/), but I was not able to find the link for the **Improve your business**. Could you share that link?

No, because they didn't provide it in a link form, but as a list of zipped files in scorm format that I [uploaded to Google drive.](https://github.com/learningequality/sushi-chef-ilo-siyb/blob/main/transform.py#L21-L27) . I know @revanthvle  has been exchanging emails to find the license that applies to this courses, but they're not available in the form of a web site as far as we know.


> 2. I'm not seeing the **[Final self-assessment](https://rise.articulate.com/share/0ZMyxNhhfd0hCuRJASzqOUSIGmvOmlKG#/lessons/i4r1fkU45UL3hm3OnA98LPSY5qqMtyeb)** resource in the **Start your business**... 🤔 Was it an oversight or a conscious decision to omit it?

Oh, no, it's just they weren't in the scorm files they passed. I'll check if it can be scrapped from the web, but being a SPA that's rendered on the fly I'm not confident the tests will be easily retrieved.


> 3. I know a lot of effort was invested into cheffing these, but we could improve the titles of the PDF resources by:
>    a. Not using the acronyms SYB, IYB, GYB, but expand them fully to **Start your business**, **Improve your business**, and **Generate your business idea** (for clarity, especially if/when the resource is saved locally).
>    b. Removing the `.pdf` ( filename≠title 😉 )

Sure, I'll do it, I didn't notice that. Being so very few pdf files I can prepare a list of the titles manually if there's not way to extract a right title from the pdf content.

**Comment by radinamatic** [comment]
> if there is any automated tool that can be passed over them to improve them, I'll do it gladly.

Don't I wish... 🙄 
(me and every other accessibility professional)

> Oh, no, it's just they weren't in the scorm files they passed. I'll check if it can be scrapped from the web, but being a SPA that's rendered on the fly I'm not confident the tests will be easily retrieved.

Understood, I thought you did scrape all from the web 🙂  

> I can prepare a list of the titles manually if there's not way to extract a right title from the pdf content.

If the files had been tagged and accessible, it would be much easier to extract proper title, but no dice in this case. You can try to set up some substitution filters, or prepare the list of titles manually as you say, since there are not that many files.

**Comment by jredrejo** [comment]
#### From @radinamatic  

> > I can prepare a list of the titles manually if there's not way to extract a right title from the pdf content.
> 
> If the files had been tagged and accessible, it would be much easier to extract proper title, but no dice in this case. You can try to set up some substitution filters, or prepare the list of titles manually as you say, since there are not that many files.

Done



#### From @lauradanforth 

> I am not sure the level of granularity I should be looking at this but looks great! Some small improvements:
> 
> - Can we change the channel name to "Start and Improve Your Business" (with that capitalization) and do we need the "ILO" at the beginning?
> 

Done

> In the Start your business folder
> 
> - There are two PDFs at the end that I suggest renaming to more userfriendly titles: "SYB-Manual.pdf" --> "Start Your Business - Manual" and "SYB-Business_plan.pdf" --> "Start Your Business - Business Plan"
> 

Done

> In the Improve your business folder
> 
> - Same comment as above for the PDF files in the "Improve your business" folder...remove the .pdf mentions

Done

> - The download buttons like in the screenshot below don't do anything for me. Is that expected? 

It's expected because kolibri does not allow downloads inside HTML5 apps. I have [filled this issue ](https://github.com/learningequality/kolibri/issues/11987)to allow it conditionally in the future but this won't be possible in the short term.


#### From @revanthvle 

> The existing PDFs are training manuals for Start and improve your business where as the course they sent is a self-paced course that learners can engage in. I am wondering if adding a folder within the channel for training manuals and moving the PDFs there makes more sense?

Done

**Comment by radinamatic** [comment]
All done, apparently!!! 💥 
Feels good that my comments were in line with those by @lauradanforth 🙂 

Updated locally, channel looks great and is ready to fly! 💯 :shipit: 🚀

**Comment by jredrejo** [comment]
@radinamatic @revanthvle I have finished cheffing the ILO - Digitalize Your Business channel. It's ready for review.
The token is daris-kutaj  and the channel url in Studio is https://studio.learningequality.org/es-es/channels/0fb3424c3b8d57deacd8d4d214270be6

@rtibbles code for this channel is available at https://github.com/learningequality/sushi-chef-ilo-dyb

**Comment by radinamatic** [comment]
@jredrejo I'll confirm if the same happens on Windows, but the resources are not displaying correctly on Ubuntu 22.04 😕 

Firefox | Chrome
-- | --
<img width="960" alt="firefox" src="https://github.com/learningequality/kolibri-library/assets/1457929/2c3a1267-21c7-4707-aa48-b6fa1448b523"> | <img width="960" alt="chrome" src="https://github.com/learningequality/kolibri-library/assets/1457929/78ca4cb2-1f5c-4f86-a9ef-8d636b368d1a">

**Comment by jredrejo** [comment]
@radinamatic can you tell me how to reproduce it? does it happen to you in some of the lessons, in all?

**Comment by radinamatic** [comment]
Just browsing the channel in the Library, haven't even tried to put it in the lesson...

**Comment by radinamatic** [comment]
Ah, update, seems to be the case just with the first resource (**Introduction - About this course**), the rest open without issues... 🤔

**Comment by jredrejo** [comment]
thanks @radinamatic it should be fixed now

**Comment by radinamatic** [comment]
Yesssss!!! 👏🏽 🙂 

<img width="960" alt="2024-04-08_18-07-21" src="https://github.com/learningequality/kolibri-library/assets/1457929/c7d55c65-e9fa-4581-8710-448ad32a8894">

I'll take another walk-through, but this should be good to go soon! 💯

**Comment by radinamatic** [comment]
Hm, one more thing I noticed: after scrolling at the bottom of the resource, the last button appears (0:30 sec in the video), but then vanishes... Is it supposed to be visible (I can't seem to manage to press it fast enough to see where it goes) or you tried to make it disappear? 😅  


https://github.com/learningequality/kolibri-library/assets/1457929/b8028ebe-782e-4c31-b308-6749ea22cf2f

**Comment by jredrejo** [comment]
@radinamatic it does not have to be visible, it's part of the code I cleaned to adapt the contents to kolibri platform. It appears for some seconds because the only way to make it disappear is.... after it appears as it's created after scrolling by the platform code.  I haven't found a better way to handle it without having access to the javascript code :shrug:

**Comment by radinamatic** [comment]
Gotcha, I had an inkling that was the case. Not a blocker, imho, just making sure 😉

**Comment by radinamatic** [comment]
Finished testing the **Digitalize Your Business** channel in Firefox/Chrome on Ubuntu 22.04, and in Firefox/Chrome/Edge on Windows 11, and it's good to go! 🎉 💯 🚀 :shipit:

**Comment by jredrejo** [comment]
Thank you @radinamatic . I 'm closing this issue now. If we receive in the future more ILO contents to chef, I'll open a new issue
